// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/__create/social-dev-shim": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/admin/export": {
    params: {};
  };
  "/cars": {
    params: {};
  };
  "/errors/async-effect-error": {
    params: {};
  };
  "/errors/event-handler-error": {
    params: {};
  };
  "/errors/hook-rule": {
    params: {};
  };
  "/errors/infinite-render-loop": {
    params: {};
  };
  "/errors/json-parse-error": {
    params: {};
  };
  "/errors/missing-component": {
    params: {};
  };
  "/errors/null-access": {
    params: {};
  };
  "/errors/render-object": {
    params: {};
  };
  "/errors/type-error-not-function": {
    params: {};
  };
  "/errors/undefined-access": {
    params: {};
  };
  "/errors/unhandled-promise": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/make-admin": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/__create/social-dev-shim" | "/account/logout" | "/account/signin" | "/account/signup" | "/admin/export" | "/cars" | "/errors/async-effect-error" | "/errors/event-handler-error" | "/errors/hook-rule" | "/errors/infinite-render-loop" | "/errors/json-parse-error" | "/errors/missing-component" | "/errors/null-access" | "/errors/render-object" | "/errors/type-error-not-function" | "/errors/undefined-access" | "/errors/unhandled-promise" | "/forgot-password" | "/make-admin" | "/reset-password" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./__create/social-dev-shim/page.jsx": {
    id: "__create/social-dev-shim/page";
    page: "/__create/social-dev-shim";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./admin/export/page.jsx": {
    id: "admin/export/page";
    page: "/admin/export";
  };
  "./cars/page.jsx": {
    id: "cars/page";
    page: "/cars";
  };
  "./errors/async-effect-error/page.jsx": {
    id: "errors/async-effect-error/page";
    page: "/errors/async-effect-error";
  };
  "./errors/event-handler-error/page.jsx": {
    id: "errors/event-handler-error/page";
    page: "/errors/event-handler-error";
  };
  "./errors/hook-rule/page.jsx": {
    id: "errors/hook-rule/page";
    page: "/errors/hook-rule";
  };
  "./errors/infinite-render-loop/page.jsx": {
    id: "errors/infinite-render-loop/page";
    page: "/errors/infinite-render-loop";
  };
  "./errors/json-parse-error/page.jsx": {
    id: "errors/json-parse-error/page";
    page: "/errors/json-parse-error";
  };
  "./errors/missing-component/page.jsx": {
    id: "errors/missing-component/page";
    page: "/errors/missing-component";
  };
  "./errors/null-access/page.jsx": {
    id: "errors/null-access/page";
    page: "/errors/null-access";
  };
  "./errors/render-object/page.jsx": {
    id: "errors/render-object/page";
    page: "/errors/render-object";
  };
  "./errors/type-error-not-function/page.jsx": {
    id: "errors/type-error-not-function/page";
    page: "/errors/type-error-not-function";
  };
  "./errors/undefined-access/page.jsx": {
    id: "errors/undefined-access/page";
    page: "/errors/undefined-access";
  };
  "./errors/unhandled-promise/page.jsx": {
    id: "errors/unhandled-promise/page";
    page: "/errors/unhandled-promise";
  };
  "./forgot-password/page.jsx": {
    id: "forgot-password/page";
    page: "/forgot-password";
  };
  "./make-admin/page.jsx": {
    id: "make-admin/page";
    page: "/make-admin";
  };
  "./reset-password/page.jsx": {
    id: "reset-password/page";
    page: "/reset-password";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.jsx");
  "page": typeof import("./src/app/./page.jsx");
  "__create/social-dev-shim/page": typeof import("./src/app/./__create/social-dev-shim/page.jsx");
  "account/logout/page": typeof import("./src/app/./account/logout/page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "account/signup/page": typeof import("./src/app/./account/signup/page.jsx");
  "admin/export/page": typeof import("./src/app/./admin/export/page.jsx");
  "cars/page": typeof import("./src/app/./cars/page.jsx");
  "errors/async-effect-error/page": typeof import("./src/app/./errors/async-effect-error/page.jsx");
  "errors/event-handler-error/page": typeof import("./src/app/./errors/event-handler-error/page.jsx");
  "errors/hook-rule/page": typeof import("./src/app/./errors/hook-rule/page.jsx");
  "errors/infinite-render-loop/page": typeof import("./src/app/./errors/infinite-render-loop/page.jsx");
  "errors/json-parse-error/page": typeof import("./src/app/./errors/json-parse-error/page.jsx");
  "errors/missing-component/page": typeof import("./src/app/./errors/missing-component/page.jsx");
  "errors/null-access/page": typeof import("./src/app/./errors/null-access/page.jsx");
  "errors/render-object/page": typeof import("./src/app/./errors/render-object/page.jsx");
  "errors/type-error-not-function/page": typeof import("./src/app/./errors/type-error-not-function/page.jsx");
  "errors/undefined-access/page": typeof import("./src/app/./errors/undefined-access/page.jsx");
  "errors/unhandled-promise/page": typeof import("./src/app/./errors/unhandled-promise/page.jsx");
  "forgot-password/page": typeof import("./src/app/./forgot-password/page.jsx");
  "make-admin/page": typeof import("./src/app/./make-admin/page.jsx");
  "reset-password/page": typeof import("./src/app/./reset-password/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};